Create poc-guidlines.md
firebolt-db/firebolt-db.github.io pull request #142
Opened 2023-05-10 14:42 UTC by GuyDuerFB

A page dedicated for PoC instructions

2023-05-10 18:15 UTC, molly-firebolt requested changes

2023-05-10 18:15 UTC, molly-firebolt commented on docs/poc-guidlines.md
> +# Firebolt POC Guidelines
We want to avoid abbreviations in docs - do you want to say "proof of concept guidelines" or perhaps "trial guidelines?

2023-05-10 18:15 UTC, molly-firebolt commented on docs/poc-guidlines.md
> +## Thank you for considering Firebolt. We created this document to help both our teams work better together during the POC.
Let's avoid first person and the somewhat meaningless word "better" whenever possible...
Rewrite: 
This document will help you through the steps to set up for a proof of concept of Firebolt. 

or something like that?

2023-05-10 18:15 UTC, molly-firebolt commented on docs/poc-guidlines.md
> +The data that will be used in the POC should be made available in an S3 region (any region is fine). Don’t hesitate to make all or a very large portion of the data available – the more data the bette
better for what? To prove the concept?

2023-05-10 18:15 UTC, molly-firebolt commented on docs/poc-guidlines.md
> +<aside>
Let's move this aside above the instructions - customers like to know why they are doing something before they do it

2023-05-10 18:15 UTC, molly-firebolt commented on docs/poc-guidlines.md
> +Send us the DDL commands that should be used in order to create the POC database schema. You can do so by saving the code into a file and sharing it with us via email or on our Slack channel.
Can we be a bit more descriptive here? Is there a specific email that they could send to, and/or a specific type of file? This paragraph assumes there is already an "us" that they have contact info for.

2023-05-10 18:15 UTC, molly-firebolt commented on docs/poc-guidlines.md
> +In order for us to know what we should benchmark against, please provide a set of queries to be executed over the selected data set. These queries should be a good representation of queries you usual
Rewrite, avoiding first person referring to Firebolt: 

Please provide a set of queries to be executed over your selected dataset, to benchmark against. These queries should be a good representation of queries you usually run, and/or queries that are slow and you would like to see improved.

2023-05-10 18:15 UTC, molly-firebolt commented on docs/poc-guidlines.md
> +You can  save the query code in a file and send it to us with the schema data. It's important for us to know how long these queries take to run in your current system.
What type of file? Is there a specific format they should share the schema in? And is it schema data or schema design?

2023-05-14 06:23 UTC, GuyDuerFB commented on docs/poc-guidlines.md
> +# Firebolt POC Guidelines
Sure - fixed

2023-05-14 06:24 UTC, GuyDuerFB commented on docs/poc-guidlines.md
> +## Thank you for considering Firebolt. We created this document to help both our teams work better together during the POC.
Sure!

2023-05-14 06:28 UTC, GuyDuerFB commented on docs/poc-guidlines.md
> +The data that will be used in the POC should be made available in an S3 region (any region is fine). Don’t hesitate to make all or a very large portion of the data available – the more data the bette
Rephrased.

2023-05-14 06:29 UTC, GuyDuerFB commented on docs/poc-guidlines.md
> +<aside>
Done

2023-05-14 06:31 UTC, GuyDuerFB commented on docs/poc-guidlines.md
> +Send us the DDL commands that should be used in order to create the POC database schema. You can do so by saving the code into a file and sharing it with us via email or on our Slack channel.
This page is going to be shared with prospects only after the intro to FB call, so there will already be an "us" :)

2023-05-14 06:34 UTC, GuyDuerFB commented on docs/poc-guidlines.md
> +In order for us to know what we should benchmark against, please provide a set of queries to be executed over the selected data set. These queries should be a good representation of queries you usual
Sure - done.

2023-05-14 06:40 UTC, GuyDuerFB commented on docs/poc-guidlines.md
> +You can  save the query code in a file and send it to us with the schema data. It's important for us to know how long these queries take to run in your current system.
I changed the section to be clearer.

2023-05-16 09:40 UTC, closed without merging